module Ros.Tests.Program

[<EntryPoint>]
let main _ =
    ArchitectureTests.tests
    @ ArtifactTests.tests
    @ PersistenceTests.tests
    @ GitTests.tests
    @ WorkTests.tests
    @ ReconciliationTests.tests
    @ WorkPlanTests.tests
    @ BacklogTests.tests
    @ TelemetryTests.tests
    @ TelemetryResolutionTests.tests
    @ ChangeSummaryTests.tests
    @ PathFilterTests.tests
    @ WorkAttributionTests.tests
    @ QueueValidationTests.tests
    @ QueuePresentationTests.tests
    @ BacklogTransitionEffectTests.tests
    @ WorkCaptureTests.tests
    @ WorkCaptureEffectTests.tests
    @ WorkUpdateTests.tests
    @ WorkUpdateEffectTests.tests
    @ WorkAttachmentTests.tests
    @ WorkAttachmentEffectTests.tests
    @ TelemetryIdentityTests.tests
    @ WorkContextEffectTests.tests
    @ WorkContextViewTests.tests
    @ WorkListViewTests.tests
    @ TelemetryValidationTests.tests
    @ FindingContractTests.tests
    @ TelemetryQueryTests.tests
    @ TelemetryLifecycleTests.tests
    @ TelemetrySummaryTests.tests
    @ TutelaTelemetryTests.tests
    @ TelemetryFinalizeTargetTests.tests
    @ TelemetryRecordMetricTests.tests
    @ TelemetryIngestTests.tests
    @ TelemetryIngestOpenAICodexTests.tests
    @ TelemetryIngestHookTests.tests
    @ TelemetryIngestClaudeStatuslineTests.tests
    @ TelemetryIngestOtelTests.tests
    @ TelemetryClassifyTests.tests
    @ TelemetryStartTests.tests
    @ AdapterContractTests.tests
    @ AdapterCallEffectTests.tests
    @ AdapterPublishEffectTests.tests
    @ LifecycleTests.tests
    @ FoundationsTests.tests
    @ OrdoObservationTests.tests
    @ ProvenanceTests.tests
    @ ProvenanceEffectTests.tests
    |> TestRunner.run
